/**
 * Content Writer Stage Prompts (Gemini 3 Flash Optimized)
 *
 * Stage 2 of the two-stage pipeline.
 * Uses PTCF framework: Persona · Task · Context · Format
 * Transforms structured data into engaging, personalized narrative.
 *
 * @module analyzer/stages/content-writer-prompts
 */

import { NO_HEDGING_DIRECTIVE } from '../shared/constants';
import type { DimensionResourceMatch } from '../../models/verbose-evaluation';

/**
 * Supported output languages for content generation
 */
export type SupportedLanguage = 'en' | 'ko' | 'ja' | 'zh';

/**
 * Result of language detection analysis
 */
export interface LanguageDetectionResult {
  /** Primary detected language */
  primary: SupportedLanguage;
  /** Confidence score (0-1) based on character ratio */
  confidence: number;
  /** Whether non-English characters were found */
  hasNonEnglish: boolean;
  /** Character counts for debug logging */
  charCounts: {
    korean: number;
    japanese: number;
    chinese: number;
    total: number;
  };
}

/**
 * Detect the primary language from given texts
 *
 * Uses Unicode character ranges to detect CJK languages:
 * - Korean (Hangul): U+AC00-U+D7AF (syllables), U+1100-U+11FF, U+3130-U+318F (Jamo)
 * - Japanese: U+3040-U+309F (Hiragana), U+30A0-U+30FF (Katakana)
 * - Chinese: U+4E00-U+9FFF (CJK Unified Ideographs)
 *
 * Priority: Korean > Japanese > Chinese > English (default)
 * Threshold: 5% - if non-English characters make up >= 5% of meaningful content,
 * the text is considered to be in that language.
 * (Lowered from 20% because developer sessions mix Korean with heavy English
 * technical content — code, CLI commands, file paths — diluting the ratio.)
 *
 * @param texts - Array of text strings to analyze
 * @returns LanguageDetectionResult with primary language and confidence
 */
const LANGUAGE_THRESHOLD = 0.05;
const EMPTY_CHAR_COUNTS = { korean: 0, japanese: 0, chinese: 0, total: 0 };

function countCharactersByRegex(text: string, regex: RegExp): number {
  return text.match(regex)?.length ?? 0;
}

function calculateCharacterCounts(text: string) {
  const korean = countCharactersByRegex(text, /[\uAC00-\uD7AF\u1100-\u11FF\u3130-\u318F]/g);
  const japanese = countCharactersByRegex(text, /[\u3040-\u309F\u30A0-\u30FF]/g);
  const chinese = countCharactersByRegex(text, /[\u4E00-\u9FFF]/g);
  const total = countCharactersByRegex(text, /[a-zA-Z0-9\uAC00-\uD7AF\u1100-\u11FF\u3130-\u318F\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FFF]/g);

  return { korean, japanese, chinese, total };
}

export function detectPrimaryLanguage(texts: string[]): LanguageDetectionResult {
  if (texts.length === 0) {
    return { primary: 'en', confidence: 1.0, hasNonEnglish: false, charCounts: EMPTY_CHAR_COUNTS };
  }

  const combinedText = texts.join(' ');
  const charCounts = calculateCharacterCounts(combinedText);

  if (charCounts.total === 0) {
    return { primary: 'en', confidence: 1.0, hasNonEnglish: false, charCounts };
  }

  const koreanRatio = charCounts.korean / charCounts.total;
  const japaneseRatio = charCounts.japanese / charCounts.total;
  const chineseRatio = charCounts.chinese / charCounts.total;
  const hasNonEnglish = charCounts.korean > 0 || charCounts.japanese > 0 || charCounts.chinese > 0;

  if (koreanRatio >= LANGUAGE_THRESHOLD) {
    return { primary: 'ko', confidence: koreanRatio, hasNonEnglish, charCounts };
  }

  if (japaneseRatio >= LANGUAGE_THRESHOLD) {
    return { primary: 'ja', confidence: japaneseRatio, hasNonEnglish, charCounts };
  }

  if (chineseRatio >= LANGUAGE_THRESHOLD && japaneseRatio < LANGUAGE_THRESHOLD) {
    return { primary: 'zh', confidence: chineseRatio, hasNonEnglish, charCounts };
  }

  const englishRatio = 1 - (koreanRatio + japaneseRatio + chineseRatio);
  return { primary: 'en', confidence: englishRatio, hasNonEnglish, charCounts };
}

/**
 * System prompt for Content Writer stage (Phase 3)
 *
 * Generates narrative-only content from Phase 2 worker outputs:
 * - topFocusAreas: Narrative-enriched focus areas (optional)
 *
 * NOTE: personalitySummary is now generated by TypeClassifier (Phase 2.5) as `reasoning`.
 * NOTE: promptPatterns generation moved to Phase 2 CommunicationPatternsWorker.
 * Phase 3 now focuses on topFocusAreas only.
 *
 * Structural data (dimensionInsights, type classification, anti-patterns,
 * critical thinking, planning, promptPatterns) is assembled deterministically
 * by evaluation-assembler from Phase 2 outputs.
 */
export const CONTENT_WRITER_SYSTEM_PROMPT_V3 = `# Persona

You are a developer career coach writing deeply personal narrative content. Think of yourself as a trusted mentor who has studied this developer's work patterns. Your role is NARRATIVE GENERATION ONLY — structural data is assembled separately.

# Task

Generate personalized narrative content using Phase 2 worker outputs. You produce ONLY:
1. **topFocusAreas** — Narrative-enriched focus areas (optional)

NOTE: personalitySummary is now generated by TypeClassifier (Phase 2.5). You do NOT generate it.
NOTE: Communication patterns (promptPatterns) are analyzed by Phase 2 CommunicationPatternsWorker.
You do NOT need to generate promptPatterns - they will be assembled from Phase 2 data.

All other data (dimensionInsights, type classification, anti-patterns, critical thinking, planning,
actionablePractices, promptPatterns, personalitySummary) is assembled from other pipeline stages. Do NOT generate these.

# Input Data Sources

Your input comes from Phase 2 specialized workers in AgentOutputs:

| Worker | Field | What it provides |
|--------|-------|------------------|
| ThinkingQuality | \`thinkingQuality\` | verificationAntiPatterns[], planningHabits[], criticalThinkingMoments[], communicationPatterns[] |
| LearningBehavior | \`learningBehavior\` | repeatedMistakePatterns[], knowledgeGaps[], learningProgressIndicators[] |
| ContextEfficiency | \`contextEfficiency\` | Token efficiency patterns |
| TypeClassifier | \`typeClassifier\` | primaryType, controlLevel, distribution |

# Output Rules

**Top 3 Focus Areas** (from learningBehavior + thinkingQuality analysis)
- Transform each priority into an engaging narrative
- Include specific action steps (START/STOP/CONTINUE)

# Format

**IMPORTANT: FLATTENED FORMAT for nested data**

**topFocusAreas.areas** - Use pipe-separated fields for actions:
- actionsData: "start_action|stop_action|continue_action" (NOT an object)

${NO_HEDGING_DIRECTIVE}`;

/**
 * Build KB context section from Phase 2.75 matched resources (DB-backed)
 *
 * Converts DimensionResourceMatch[] into a prompt section grouped by dimension.
 */
export function buildKnowledgeContextFromResources(
  resources: DimensionResourceMatch[]
): string {
  if (!resources || resources.length === 0) {
    return '';
  }

  const header = `## Knowledge Base Context (for tip generation)\n\nReference these expert insights when writing tips. Use natural attribution: "According to Anthropic's guide...", "As Simon Willison advises..."\n`;

  const sections: string[] = [header];

  for (const match of resources) {
    const hasInsights = match.professionalInsights.length > 0;
    const hasKnowledge = match.knowledgeItems.length > 0;
    if (!hasInsights && !hasKnowledge) continue;

    sections.push(`### ${match.dimensionDisplayName}\n`);

    for (const insight of match.professionalInsights) {
      sections.push(`- **"${insight.title}"** (${insight.sourceAuthor}): "${insight.keyTakeaway}"`);
      if (insight.actionableAdvice.length > 0) {
        sections.push(`  - Advice: ${insight.actionableAdvice.slice(0, 2).join('; ')}`);
      }
    }

    for (const item of match.knowledgeItems) {
      const author = item.sourceAuthor || 'Unknown';
      sections.push(`- **"${item.title}"** (${author}): "${item.summary}"`);
    }

    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Language display names for output instructions
 */
export const LANGUAGE_DISPLAY_NAMES: Record<SupportedLanguage, string> = {
  en: 'English',
  ko: 'Korean',
  ja: 'Japanese',
  zh: 'Chinese',
};

/**
 * Build the user prompt for Content Writer stage (Phase 3)
 *
 * Constructs a prompt from Phase 2 worker outputs for narrative generation.
 *
 * NOTE: personalitySummary is now generated by TypeClassifier (Phase 2.5).
 * NOTE: promptPatterns generation moved to Phase 2 CommunicationPatternsWorker.
 * Phase 3 now focuses on topFocusAreas only.
 *
 * @param agentOutputsSummary - Structured text summary of Phase 2 + 2.5 agent outputs
 * @param sessionCount - Number of sessions analyzed
 * @param knowledgeResources - Optional DB-backed knowledge resources from Phase 2.75
 * @param topUtterances - Kept for signature compatibility (no longer used for personalitySummary)
 */
export function buildContentWriterUserPromptV3(
  agentOutputsSummary: string,
  sessionCount: number,
  knowledgeResources?: DimensionResourceMatch[],
  topUtterances?: Array<{ id: string; text: string; wordCount: number }>
): string {
  const kbContextSection = knowledgeResources
    ? buildKnowledgeContextFromResources(knowledgeResources)
    : '';

  return `# Context Data

This developer has ${sessionCount} sessions analyzed.

## Phase 2 Analysis Outputs (Structured Summary from Specialized Workers)

Below is a structured summary from 4 Phase 2 workers + 1 Phase 2.5 worker.
Each section uses ## headers with key scores.

NOTE: personalitySummary is generated by TypeClassifier (Phase 2.5). Do NOT generate it.
NOTE: Communication patterns (promptPatterns) are analyzed by CommunicationPatternsWorker in Phase 2. Do NOT generate them.

${agentOutputsSummary}
${kbContextSection}
# Generation Instructions

You generate ONLY topFocusAreas. personalitySummary and promptPatterns are handled by other pipeline stages.

1. **Top 3 Focus Areas** (from learningBehavior + thinkingQuality analysis)
   - Create ranked focus areas with narrative and actions (start/stop/continue)
   - actionsData format: "start_action|stop_action|continue_action"

Do NOT generate personalitySummary or promptPatterns.`;
}
