export { HeroSection } from './HeroSection';
export { PhilosophySection } from './PhilosophySection';
export { ValueStory } from './ValueStory';
export { AnalysisShowcase } from './AnalysisShowcase';
export { PatternExampleCard } from './PatternExampleCard';
export { KnowledgeSection } from './KnowledgeSection';
export { DownloadSection } from './DownloadSection';
export { LandingFooter } from './LandingFooter';
export { WaitlistModal, waitlistConfigs } from './WaitlistModal';
export type { WaitlistConfig, WaitlistType } from './WaitlistModal';
