/**
 * Footer Component
 *
 * Renders the report footer with save path and links.
 */

import pc from 'picocolors';
import { divider } from '../theme';

/**
 * Render the report footer
 */
export function renderFooter(savePath?: string): string {
  const lines: string[] = [];

  lines.push(divider(60));
  lines.push('');

  if (savePath) {
    lines.push(pc.dim(`  Report saved: ${savePath}`));
  }

  lines.push(
    pc.dim('  Run ') +
      pc.cyan('noslop history') +
      pc.dim(' to see past analyses')
  );
  lines.push('');
  lines.push(
    pc.dim('  Generated by NoMoreAISlop • github.com/nomoreaislop/nomoreaislop')
  );
  lines.push('');

  return lines.join('\n');
}
