/**
 * Remote Report Page
 *
 * Displays analysis results from a shareable URL (e.g., /r/jmjV2UnU)
 * Generated by CLI after uploading analysis to Supabase.
 *
 * States:
 * - Loading: Fetching result from API
 * - Error (404): Result not found
 * - Error (410): Result expired
 * - Success (paid): Full TabbedReportContainer
 * - Success (free): Preview data + UnlockSection paywall
 */

import { Suspense } from 'react';
import type { Metadata } from 'next';
import styles from './page.module.css';

// Client component for data fetching
import { RemoteReportContent } from './RemoteReportContent';

const BASE_URL = process.env.NOSLOP_BASE_URL || 'https://www.nomoreaislop.app';

interface PageProps {
  params: Promise<{ resultId: string }>;
}

/**
 * Generate metadata for SEO and social sharing
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { resultId } = await params;

  // Default metadata - can be enhanced by fetching result server-side
  const title = 'AI Coding Style Report | NoMoreAISlop';
  const description =
    'Discover your AI collaboration type and get personalized insights to improve your developer-AI workflow.';

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: 'website',
      url: `${BASE_URL}/r/${resultId}`,
      siteName: 'NoMoreAISlop',
      images: [
        {
          url: `${BASE_URL}/og-image.png`,
          width: 1200,
          height: 630,
          alt: 'NoMoreAISlop - AI Coding Style Analysis',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [`${BASE_URL}/og-image.png`],
    },
  };
}

/**
 * Loading fallback component
 */
function LoadingFallback() {
  return (
    <div className={styles.page}>
      <div className={styles.loadingContainer}>
        <div className={styles.spinner} />
        <p className={styles.loadingText}>Loading your analysis...</p>
      </div>
    </div>
  );
}

/**
 * Remote Report Page - Server Component
 */
export default async function RemoteReportPage({ params }: PageProps) {
  const { resultId } = await params;

  return (
    <Suspense fallback={<LoadingFallback />}>
      <RemoteReportContent resultId={resultId} />
    </Suspense>
  );
}
