/**
 * Remote Report Page
 *
 * Displays analysis results from a shareable URL (e.g., /r/jmjV2UnU)
 * Generated by CLI after sending analysis data to the self-hosted server.
 *
 * States:
 * - Loading: Fetching result from API
 * - Error (404): Result not found
 * - Error (410): Result expired
 * - Success: Full TabbedReportContainer
 */

import { Suspense } from 'react';
import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { buildAbsoluteSiteUrl, resolveSiteOrigin } from '@/lib/site-origin';
import styles from './page.module.css';

// Client component for data fetching
import { RemoteReportContent } from './RemoteReportContent';

interface PageProps {
  params: Promise<{ resultId: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { resultId } = await params;
  const headerStore = await headers();
  const origin = resolveSiteOrigin({
    host: headerStore.get('host'),
    forwardedHost: headerStore.get('x-forwarded-host'),
    forwardedProto: headerStore.get('x-forwarded-proto'),
    origin: headerStore.get('origin'),
    referer: headerStore.get('referer'),
  });

  const title = 'Self-Hosted AI Builder Report | BetterPrompt';
  const description =
    'See exactly where your AI workflow breaks down with a report generated by your own self-hosted server.';
  const imageUrl = buildAbsoluteSiteUrl(`/r/${resultId}/opengraph-image`, origin);

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: 'website',
      url: buildAbsoluteSiteUrl(`/r/${resultId}`, origin),
      siteName: 'BetterPrompt',
      images: [
        {
          url: imageUrl,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [imageUrl],
    },
  };
}

function LoadingFallback() {
  return (
    <div className={styles.page}>
      <div className={styles.loadingContainer}>
        <div className={styles.spinner} />
        <p className={styles.loadingText}>Loading your analysis...</p>
      </div>
    </div>
  );
}

export default async function RemoteReportPage({ params }: PageProps) {
  const { resultId } = await params;

  return (
    <Suspense fallback={<LoadingFallback />}>
      <RemoteReportContent resultId={resultId} />
    </Suspense>
  );
}
